# Generated by Django 3.2.9 on 2021-11-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20211130_1333'),
        ('users', '0002_alter_profile_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bookmark',
            field=models.ManyToManyField(blank=True, to='recipe.Recipe'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='vegan',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='disliked',
        ),
        migrations.AddField(
            model_name='profile',
            name='disliked',
            field=models.ManyToManyField(blank=True, to='recipe.Ingredients'),
        ),
    ]
