# Generated by Django 3.2.6 on 2021-11-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
