# Generated by Django 3.2.9 on 2021-11-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20211130_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='thumb',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='steps',
            name='img',
            field=models.TextField(blank=True),
        ),
    ]
